from __future__ import annotations

from copy import deepcopy
from typing import Any


# HTML V12/V13 화면에 이미 구현되어 있는 서식 구조를 Python 출력엔진의
# 기준 계약으로 명시한다. 계산 규칙은 이 파일에서 재계산하지 않는다.
#
# Stage 16부터 print 프로필은 HWPX의 한컴 인쇄배치 기준을 명시한다.
# 원본 HTML의 시각적 의도를 보존하되 업무 계산은 여기서 수행하지 않는다.
FORMAT_CONTRACTS: dict[str, dict[str, Any]] = {
    "pay_slip": {
        "label": "활동비 지급 명세서",
        "source": {
            "file": "legacy-js/10-ext-v99.js",
            "function": "buildPaySlipHtml / exportPaySlipXlsx",
        },
        "title": "활동비 지급 명세서 ({ym})",
        "sheet": "지급명세서",
        "meta": ["수령인", "소속", "발행일"],
        "columns": ["날짜", "구분", "학생/제목", "학교", "시간/회차", "내용", "단가", "지급액"],
        "columnWidths": [12, 10, 16, 16, 14, 22, 12, 12],
        "summary": ["학습코칭 소계", "수업협력 소계", "출장비 소계", "세전 지급액", "공제액", "실지급액"],
        "htmlClass": "pay-doc",
        "print": {
            "orientation": "portrait",
            "marginMm": {"left": 13, "right": 13, "top": 14, "bottom": 14},
            "titlePt": 17,
            "bodyPt": 8.5,
            "headerPt": 8.5,
            "smallPt": 7.5,
            "defaultRowMm": 7.0,
            "cellMarginMm": {"left": 1.1, "right": 1.1, "top": 0.6, "bottom": 0.6},
            "repeatHeader": True,
            "singlePageTarget": False,
        },
    },
    "execution_report": {
        "label": "월별 활동비 집행내역서",
        "source": {
            "file": "legacy-js/10-ext-v99.js",
            "function": "buildExecReportHtml / exportExecReportXlsx",
        },
        "title": "월별 활동비 집행내역서 ({ym})",
        "sheet": "집행내역서",
        "meta": ["기관", "대상", "발행일"],
        "columns": [
            "No", "지원단", "코칭(회)", "코칭금액", "협력(회)", "협력금액",
            "출장(회)", "출장금액", "합계(세전)", "비고",
        ],
        "columnWidths": [5, 12, 10, 14, 10, 14, 10, 14, 14, 16],
        "summary": ["합계"],
        "htmlClass": "pay-doc",
        "landscape": True,
        "print": {
            "orientation": "landscape",
            "marginMm": {"left": 9, "right": 9, "top": 9, "bottom": 9},
            "titlePt": 16,
            "bodyPt": 8.0,
            "headerPt": 8.0,
            "smallPt": 7.2,
            "defaultRowMm": 6.4,
            "cellMarginMm": {"left": 0.8, "right": 0.8, "top": 0.45, "bottom": 0.45},
            "repeatHeader": True,
            "singlePageTarget": False,
        },
    },
    "manager_book": {
        "label": "학습지원단 관리부",
        "source": {
            "file": "legacy-js/08-forms.js",
            "function": "buildMgrBookHtml / exportMgrBookXlsx",
        },
        "title": "학습지원단 관리부 ({year}년 {month}월)",
        "sheet": "관리부",
        "meta": ["소속", "성명", "연락처", "담당학생"],
        "layout": {
            "type": "two-half-month-columns",
            "leftDays": [1, 16],
            "rightDays": [17, 31],
            "rows": 16,
            "separatorColumn": 7,
        },
        "columns": [
            "일", "요일", "학교", "시간", "지도내용", "학생", "",
            "일", "요일", "학교", "시간", "지도내용", "학생",
        ],
        "columnWidths": [4, 5, 12, 12, 24, 10, 2, 4, 5, 12, 12, 24, 10],
        "summary": ["총 실시 회기", "총 시수", "확인자"],
        "htmlClass": "mgr-book",
        "verifiedStatuses": ["verified", "paid"],
        "landscape": True,
        "print": {
            "orientation": "landscape",
            "marginMm": {"left": 8, "right": 8, "top": 8, "bottom": 8},
            "titlePt": 15,
            "bodyPt": 7.4,
            "headerPt": 7.4,
            "smallPt": 6.8,
            "defaultRowMm": 6.0,
            "cellMarginMm": {"left": 0.6, "right": 0.6, "top": 0.35, "bottom": 0.35},
            "repeatHeader": True,
            "singlePageTarget": True,
        },
    },
    "staff_appoint": {
        "label": "위촉장",
        "source": {"file": "legacy-js/12-patches.js", "function": "openForm('staff-appoint')"},
        "title": "위 촉 장",
        "sheet": "위촉장",
        "columns": ["항목", "내용", "항목", "내용"],
        "columnWidths": [15, 25, 15, 25],
        "showHeader": False,
        "labelColumns": [0, 2],
        "issuer": "교육지원청교육장",
        "print": {
            "orientation": "portrait",
            "marginMm": {"left": 18, "right": 18, "top": 18, "bottom": 18},
            "titlePt": 22,
            "bodyPt": 10,
            "headerPt": 10,
            "smallPt": 8,
            "issuerPt": 18,
            "defaultRowMm": 10,
            "titleGapMm": 7,
            "cellMarginMm": {"left": 1.8, "right": 1.8, "top": 1.1, "bottom": 1.1},
            "mergeEmptyTail": True,
            "singlePageTarget": True,
        },
    },
    "appoint_confirm": {
        "label": "위촉 확인서",
        "source": {"file": "legacy-js/12-patches.js", "function": "openForm('appoint-confirm')"},
        "title": "위촉 확인서",
        "sheet": "위촉확인서",
        "columns": ["항목", "내용", "항목", "내용"],
        "columnWidths": [15, 25, 15, 25],
        "showHeader": False,
        "labelColumns": [0, 2],
        "issuer": "교육지원청교육장",
        "print": {
            "orientation": "portrait",
            "marginMm": {"left": 17, "right": 17, "top": 16, "bottom": 16},
            "titlePt": 20,
            "bodyPt": 9.5,
            "headerPt": 9.5,
            "smallPt": 8,
            "issuerPt": 17,
            "defaultRowMm": 9,
            "titleGapMm": 5,
            "cellMarginMm": {"left": 1.6, "right": 1.6, "top": 0.9, "bottom": 0.9},
            "mergeEmptyTail": True,
            "singlePageTarget": True,
        },
    },
    "career_confirm": {
        "label": "경력 확인서",
        "source": {"file": "legacy-js/12-patches.js", "function": "openForm('career-confirm')"},
        "title": "경력 확인서",
        "sheet": "경력확인서",
        "infoColumns": ["항목", "내용", "항목", "내용"],
        "infoColumnWidths": [15, 25, 15, 25],
        "columns": ["No", "분야", "위촉 기간", "기간", "실시 회기", "시수"],
        "columnWidths": [6, 15, 28, 10, 10, 10],
        "verifiedStatuses": ["verified", "paid"],
        "issuer": "교육지원청교육장",
        "print": {
            "orientation": "portrait",
            "marginMm": {"left": 15, "right": 15, "top": 14, "bottom": 14},
            "titlePt": 19,
            "bodyPt": 8.7,
            "headerPt": 8.7,
            "smallPt": 7.5,
            "issuerPt": 16,
            "defaultRowMm": 7.4,
            "titleGapMm": 4,
            "cellMarginMm": {"left": 1.1, "right": 1.1, "top": 0.7, "bottom": 0.7},
            "mergeEmptyTail": True,
            "repeatHeader": True,
            "singlePageTarget": True,
        },
    },
    "resign": {
        "label": "해촉 신청서",
        "source": {"file": "legacy-js/12-patches.js", "function": "openForm('resign')"},
        "title": "해촉 신청서",
        "sheet": "해촉신청서",
        "columns": ["항목", "내용", "항목", "내용"],
        "columnWidths": [15, 25, 15, 25],
        "showHeader": False,
        "labelColumns": [0, 2],
        "issuer": "교육지원청교육장",
        "print": {
            "orientation": "portrait",
            "marginMm": {"left": 16, "right": 16, "top": 14, "bottom": 14},
            "titlePt": 20,
            "bodyPt": 9.2,
            "headerPt": 9.2,
            "smallPt": 7.8,
            "issuerPt": 15,
            "defaultRowMm": 8.0,
            "titleGapMm": 4,
            "cellMarginMm": {"left": 1.4, "right": 1.4, "top": 0.8, "bottom": 0.8},
            "mergeEmptyTail": True,
            "singlePageTarget": True,
        },
    },
    "plan_doc": {
        "label": "학습지도계획서",
        "source": {"file": "legacy-js/08-forms.js", "function": "openForm('plan-doc')"},
        "title": "학습지도계획서",
        "sheet": "학습지도계획서",
        "columns": ["항목", "내용", "항목", "내용"],
        "columnWidths": [15, 25, 15, 25],
        "showHeader": False,
        "labelColumns": [0, 2],
        "blankSections": ["학습목표", "지도계획", "평가방법"],
        "print": {
            "orientation": "portrait",
            "marginMm": {"left": 14, "right": 14, "top": 12, "bottom": 12},
            "titlePt": 18,
            "bodyPt": 9.0,
            "headerPt": 9.0,
            "smallPt": 7.5,
            "defaultRowMm": 7.5,
            "titleGapMm": 3,
            "cellMarginMm": {"left": 1.3, "right": 1.3, "top": 0.8, "bottom": 0.8},
            "mergeEmptyTail": True,
            "mergeBlankRows": True,
            "singlePageTarget": True,
        },
    },
    "timetable": {
        "label": "주간 시간표",
        "source": {
            "file": "legacy-js/08-forms.js",
            "function": "buildTTGrid / exportTTXlsx",
        },
        "title": "{title}",
        "sheet": "시간표",
        "columns": ["시간", "월", "화", "수", "목", "금", "토", "일"],
        "columnWidths": [8, 22, 22, 22, 22, 22, 22, 22],
        "days": ["월", "화", "수", "목", "금", "토", "일"],
        "startHour": 8,
        "endHour": 22,
        "stepMinutes": 30,
        "landscape": True,
        "print": {
            "orientation": "landscape",
            "marginMm": {"left": 7, "right": 7, "top": 7, "bottom": 7},
            "titlePt": 14,
            "bodyPt": 6.8,
            "headerPt": 7.2,
            "smallPt": 6.2,
            "defaultRowMm": 5.0,
            "titleGapMm": 1.5,
            "tableGapMm": 1.0,
            "cellMarginMm": {"left": 0.45, "right": 0.45, "top": 0.25, "bottom": 0.25},
            "repeatHeader": True,
            "singlePageTarget": True,
        },
    },
}


def get_format_contract(key: str) -> dict[str, Any]:
    if key not in FORMAT_CONTRACTS:
        raise KeyError(key)
    return deepcopy(FORMAT_CONTRACTS[key])


def list_format_contracts() -> dict[str, dict[str, Any]]:
    return deepcopy(FORMAT_CONTRACTS)
